### ISSUE TITLE
Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by JohnatanNorman** [cferdinandi/gumshoe#105] opened 2019-06-06 20:07 UTC
Not sure what happens, but I was using gatsbyjs and your other library (smooth-scroll) and it works wonders. Both of them were required the same way: I was checking if window object (gatsbyjs thing) exists and registering gumshoe like so
```
const Gumshoe = require('gumshoejs');
const spy = new Gumshoe('#sidenav a');
```
sidenav is of course the id of ul. Any ideas what is causing that?

UPDATE: var doesn't change anything of course, because it's scoped to the page.

**Comment by cferdinandi** [comment] 2019-06-07 01:45
Reduced test case please: https://github.com/cferdinandi/gumshoe/blob/master/.github/contributing.md

**Comment by cferdinandi** [comment] 2019-06-13 02:54
Closing due to non-response. Will reopen if a reduced test case is provided.

**Closed by cferdinandi** 2019-06-13 02:54 UTC
Labels: bug

**Comment by mikemartin** [comment] 2019-11-12 01:18
@JohnatanNorman I had this error when my `#sidenav` ID didn't exist it my template, causing the `navItems` array to be empty.

**Comment by matthew-ia** [comment] 2021-05-07 21:29
Also having this issue. 

**Edit:** I initially supplied test case in this comment, but I've found it was invalid, so I've removed it. Will open a new issue if I can accurately reproduce. I do believe this may be related to frameworks which mount/remount, e.g. React (OP mentioned Gatsby). I'm using Svelte, and the issue I'm experiencing actually occurs when a link inside of the spy list has an `href` that is an id, but that id doesn't exist anywhere on the page.

**Comment by marco910** [comment] 2022-03-12 12:55
If you're using it with React you have to call `const spy = new Gumshoe('#sidenav a');` inside `useEffect`
